sudo: required
language: r
warnings_are_errors: false
dist: trusty

r_packages:
  - testthat
  - covr

after_success:
  - Rscript -e "covr::codecov()"

email:
  on_success: change
  on_failure: change
